version: '3' # версия синтаксиса
services:
  express-app: # Сервер Express
    build: .
    ports:
      - '3000:3000'
  react-app: # React-приложение
    build: ../client # Путь к вашему React-приложению относительно корня вашего проекта
    ports:
      - '80:80' # Порт, на котором будет доступно ваше React-приложение
      - '8000:8000' # Порт, на котором будет доступно ваше React-приложение
